export const SkillsData = [
  {
    name: "HTML",
    icon: "/icons/html5.svg",
    color: "#E34F26",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    name: "CSS",
    icon: "/icons/css3.svg",
    color: "#1572B6",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  {
    name: "JavaScript",
    icon: "/icons/javascript.svg",
    color: "#F7DF1E",
    url: "https://developer.mozilla.org/en-US/docs/Web/javascript",
  },
  {
    name: "TypeScript",
    icon: "/icons/typescript.svg",
    color: "#3178C6",
    url: "https://www.typescriptlang.org/",
  },
  {
    name: "React",
    icon: "/icons/react.svg",
    color: "#61DAFB",
    url: "https://reactjs.org/",
  },
  {
    name: "Next.js",
    icon: "/icons/nextjs.svg",
    color: "#fff",
    url: "https://nextjs.org/",
  },
  {
    name: "Tailwind CSS",
    icon: "/icons/tailwindcss.svg",
    url: "https://tailwindcss.com",
    color: "#06B6D4",
  },
  {
    name: "Bootstrap",
    icon: "/icons/bootstrap.svg",
    url: "https://getbootstrap.com/",
    color: "#06B6D4",
  },
  {
    name: "SASS",
    icon: "/icons/sass.svg",
    url: "https://sass-lang.com/",
    color: "#06B6D4",
  },
  {
    name: "Supabase",
    icon: "/icons/supabase.svg",
    color: "#3ECF8E",
    url: "https://supabase.com",
  },
  {
    name: "Appwrite",
    icon: "/icons/appwrite.svg",
    color: "#3ECF8E",
    url: "https://appwrite.io/",
  },
  {
    name: "C",
    icon: "/icons/c.svg",
    color: "#3ECF8E",
    url: "https://www.learn-c.org/",
  },
  {
    name: "Github",
    icon: "/icons/github.svg",
    color: "#3ECF8E",
    url: "https://github.com/",
  },
  {
    name: "Java",
    icon: "/icons/java.svg",
    color: "#3ECF8E",
    url: "https://www.java.com/en/",
  },
  {
    name: "material-ui",
    icon: "/icons/materialui.svg",
    color: "#3ECF8E",
    url: "https://mui.com/material-ui/",
  },
  {
    name: "Oracle",
    icon: "/icons/oracle.svg",
    color: "#3ECF8E",
    url: "https://www.oracle.com/",
  },
  {
    name: "Postman",
    icon: "/icons/postman.svg",
    color: "#3ECF8E",
    url: "https://www.postman.com/",
  },
  {
    name: "Python",
    icon: "/icons/python.svg",
    color: "#3ECF8E",
    url: "https://www.python.org/",
  },
  {
    name: "vitejs",
    icon: "/icons/vitejs.svg",
    color: "#3ECF8E",
    url: "https://vitejs.dev/",
  },
  {
    name: "vscode",
    icon: "/icons/vscode.svg",
    color: "#3ECF8E",
    url: "https://code.visualstudio.com/",
  },
];
